// The file paths are relative to the other Interlinear XML files.
const interlinearXMLs = [
  '../../Interlinear/01-Genesis/chapter-001.xml',
  '../../Interlinear/01-Genesis/chapter-002.xml',
  '../../Interlinear/01-Genesis/chapter-003.xml',
  '../../Interlinear/01-Genesis/chapter-004.xml',
  '../../Interlinear/01-Genesis/chapter-005.xml',
  '../../Interlinear/01-Genesis/chapter-006.xml',
  '../../Interlinear/01-Genesis/chapter-007.xml',
  '../../Interlinear/01-Genesis/chapter-008.xml',
  '../../Interlinear/01-Genesis/chapter-009.xml',
  '../../Interlinear/01-Genesis/chapter-010.xml',
  '../../Interlinear/01-Genesis/chapter-011.xml',
  '../../Interlinear/01-Genesis/chapter-012.xml',
  '../../Interlinear/01-Genesis/chapter-013.xml',
  '../../Interlinear/01-Genesis/chapter-014.xml',
  '../../Interlinear/01-Genesis/chapter-015.xml',
  '../../Interlinear/01-Genesis/chapter-016.xml',
  '../../Interlinear/01-Genesis/chapter-017.xml',
  '../../Interlinear/01-Genesis/chapter-018.xml',
  '../../Interlinear/01-Genesis/chapter-019.xml',
  '../../Interlinear/01-Genesis/chapter-020.xml',
  '../../Interlinear/01-Genesis/chapter-021.xml',
  '../../Interlinear/01-Genesis/chapter-022.xml',
  '../../Interlinear/01-Genesis/chapter-023.xml',
  '../../Interlinear/01-Genesis/chapter-024.xml',
  '../../Interlinear/01-Genesis/chapter-025.xml',
  '../../Interlinear/01-Genesis/chapter-026.xml',
  '../../Interlinear/01-Genesis/chapter-027.xml',
  '../../Interlinear/01-Genesis/chapter-028.xml',
  '../../Interlinear/01-Genesis/chapter-029.xml',
  '../../Interlinear/01-Genesis/chapter-030.xml',
  '../../Interlinear/01-Genesis/chapter-031.xml',
  '../../Interlinear/01-Genesis/chapter-032.xml',
  '../../Interlinear/01-Genesis/chapter-033.xml',
  '../../Interlinear/01-Genesis/chapter-034.xml',
  '../../Interlinear/01-Genesis/chapter-035.xml',
  '../../Interlinear/01-Genesis/chapter-036.xml',
  '../../Interlinear/01-Genesis/chapter-037.xml',
  '../../Interlinear/01-Genesis/chapter-038.xml',
  '../../Interlinear/01-Genesis/chapter-039.xml',
  '../../Interlinear/01-Genesis/chapter-040.xml',
  '../../Interlinear/01-Genesis/chapter-041.xml',
  '../../Interlinear/01-Genesis/chapter-042.xml',
  '../../Interlinear/01-Genesis/chapter-043.xml',
  '../../Interlinear/01-Genesis/chapter-044.xml',
  '../../Interlinear/01-Genesis/chapter-045.xml',
  '../../Interlinear/01-Genesis/chapter-046.xml',
  '../../Interlinear/01-Genesis/chapter-047.xml',
  '../../Interlinear/01-Genesis/chapter-048.xml',
  '../../Interlinear/01-Genesis/chapter-049.xml',
  '../../Interlinear/01-Genesis/chapter-050.xml',
  '../../Interlinear/02-Exodus/chapter-001.xml',
  '../../Interlinear/02-Exodus/chapter-002.xml',
  '../../Interlinear/02-Exodus/chapter-003.xml',
  '../../Interlinear/02-Exodus/chapter-004.xml',
  '../../Interlinear/02-Exodus/chapter-005.xml',
  '../../Interlinear/02-Exodus/chapter-006.xml',
  '../../Interlinear/02-Exodus/chapter-007.xml',
  '../../Interlinear/02-Exodus/chapter-008.xml',
  '../../Interlinear/02-Exodus/chapter-009.xml',
  '../../Interlinear/02-Exodus/chapter-010.xml',
  '../../Interlinear/02-Exodus/chapter-011.xml',
  '../../Interlinear/02-Exodus/chapter-012.xml',
  '../../Interlinear/02-Exodus/chapter-013.xml',
  '../../Interlinear/02-Exodus/chapter-014.xml',
  '../../Interlinear/02-Exodus/chapter-015.xml',
  '../../Interlinear/02-Exodus/chapter-016.xml',
  '../../Interlinear/02-Exodus/chapter-017.xml',
  '../../Interlinear/02-Exodus/chapter-018.xml',
  '../../Interlinear/02-Exodus/chapter-019.xml',
  '../../Interlinear/02-Exodus/chapter-020.xml',
  '../../Interlinear/02-Exodus/chapter-021.xml',
  '../../Interlinear/02-Exodus/chapter-022.xml',
  '../../Interlinear/02-Exodus/chapter-023.xml',
  '../../Interlinear/02-Exodus/chapter-024.xml',
  '../../Interlinear/02-Exodus/chapter-025.xml',
  '../../Interlinear/02-Exodus/chapter-026.xml',
  '../../Interlinear/02-Exodus/chapter-027.xml',
  '../../Interlinear/02-Exodus/chapter-028.xml',
  '../../Interlinear/02-Exodus/chapter-029.xml',
  '../../Interlinear/02-Exodus/chapter-030.xml',
  '../../Interlinear/02-Exodus/chapter-031.xml',
  '../../Interlinear/02-Exodus/chapter-032.xml',
  '../../Interlinear/02-Exodus/chapter-033.xml',
  '../../Interlinear/02-Exodus/chapter-034.xml',
  '../../Interlinear/02-Exodus/chapter-035.xml',
  '../../Interlinear/02-Exodus/chapter-036.xml',
  '../../Interlinear/02-Exodus/chapter-037.xml',
  '../../Interlinear/02-Exodus/chapter-038.xml',
  '../../Interlinear/02-Exodus/chapter-039.xml',
  '../../Interlinear/02-Exodus/chapter-040.xml',
  '../../Interlinear/03-Leviticus/chapter-001.xml',
  '../../Interlinear/03-Leviticus/chapter-002.xml',
  '../../Interlinear/03-Leviticus/chapter-003.xml',
  '../../Interlinear/03-Leviticus/chapter-004.xml',
  '../../Interlinear/03-Leviticus/chapter-005.xml',
  '../../Interlinear/03-Leviticus/chapter-006.xml',
  '../../Interlinear/03-Leviticus/chapter-007.xml',
  '../../Interlinear/03-Leviticus/chapter-008.xml',
  '../../Interlinear/03-Leviticus/chapter-009.xml',
  '../../Interlinear/03-Leviticus/chapter-010.xml',
  '../../Interlinear/03-Leviticus/chapter-011.xml',
  '../../Interlinear/03-Leviticus/chapter-012.xml',
  '../../Interlinear/03-Leviticus/chapter-013.xml',
  '../../Interlinear/03-Leviticus/chapter-014.xml',
  '../../Interlinear/03-Leviticus/chapter-015.xml',
  '../../Interlinear/03-Leviticus/chapter-016.xml',
  '../../Interlinear/03-Leviticus/chapter-017.xml',
  '../../Interlinear/03-Leviticus/chapter-018.xml',
  '../../Interlinear/03-Leviticus/chapter-019.xml',
  '../../Interlinear/03-Leviticus/chapter-020.xml',
  '../../Interlinear/03-Leviticus/chapter-021.xml',
  '../../Interlinear/03-Leviticus/chapter-022.xml',
  '../../Interlinear/03-Leviticus/chapter-023.xml',
  '../../Interlinear/03-Leviticus/chapter-024.xml',
  '../../Interlinear/03-Leviticus/chapter-025.xml',
  '../../Interlinear/03-Leviticus/chapter-026.xml',
  '../../Interlinear/03-Leviticus/chapter-027.xml',
  '../../Interlinear/04-Numbers/chapter-001.xml',
  '../../Interlinear/04-Numbers/chapter-002.xml',
  '../../Interlinear/04-Numbers/chapter-003.xml',
  '../../Interlinear/04-Numbers/chapter-004.xml',
  '../../Interlinear/04-Numbers/chapter-005.xml',
  '../../Interlinear/04-Numbers/chapter-006.xml',
  '../../Interlinear/04-Numbers/chapter-007.xml',
  '../../Interlinear/04-Numbers/chapter-008.xml',
  '../../Interlinear/04-Numbers/chapter-009.xml',
  '../../Interlinear/04-Numbers/chapter-010.xml',
  '../../Interlinear/04-Numbers/chapter-011.xml',
  '../../Interlinear/04-Numbers/chapter-012.xml',
  '../../Interlinear/04-Numbers/chapter-013.xml',
  '../../Interlinear/04-Numbers/chapter-014.xml',
  '../../Interlinear/04-Numbers/chapter-015.xml',
  '../../Interlinear/04-Numbers/chapter-016.xml',
  '../../Interlinear/04-Numbers/chapter-017.xml',
  '../../Interlinear/04-Numbers/chapter-018.xml',
  '../../Interlinear/04-Numbers/chapter-019.xml',
  '../../Interlinear/04-Numbers/chapter-020.xml',
  '../../Interlinear/04-Numbers/chapter-021.xml',
  '../../Interlinear/04-Numbers/chapter-022.xml',
  '../../Interlinear/04-Numbers/chapter-023.xml',
  '../../Interlinear/04-Numbers/chapter-024.xml',
  '../../Interlinear/04-Numbers/chapter-025.xml',
  '../../Interlinear/04-Numbers/chapter-026.xml',
  '../../Interlinear/04-Numbers/chapter-027.xml',
  '../../Interlinear/04-Numbers/chapter-028.xml',
  '../../Interlinear/04-Numbers/chapter-029.xml',
  '../../Interlinear/04-Numbers/chapter-030.xml',
  '../../Interlinear/04-Numbers/chapter-031.xml',
  '../../Interlinear/04-Numbers/chapter-032.xml',
  '../../Interlinear/04-Numbers/chapter-033.xml',
  '../../Interlinear/04-Numbers/chapter-034.xml',
  '../../Interlinear/04-Numbers/chapter-035.xml',
  '../../Interlinear/04-Numbers/chapter-036.xml',
  '../../Interlinear/05-Deuteronomy/chapter-001.xml',
  '../../Interlinear/05-Deuteronomy/chapter-002.xml',
  '../../Interlinear/05-Deuteronomy/chapter-003.xml',
  '../../Interlinear/05-Deuteronomy/chapter-004.xml',
  '../../Interlinear/05-Deuteronomy/chapter-005.xml',
  '../../Interlinear/05-Deuteronomy/chapter-006.xml',
  '../../Interlinear/05-Deuteronomy/chapter-007.xml',
  '../../Interlinear/05-Deuteronomy/chapter-008.xml',
  '../../Interlinear/05-Deuteronomy/chapter-009.xml',
  '../../Interlinear/05-Deuteronomy/chapter-010.xml',
  '../../Interlinear/05-Deuteronomy/chapter-011.xml',
  '../../Interlinear/05-Deuteronomy/chapter-012.xml',
  '../../Interlinear/05-Deuteronomy/chapter-013.xml',
  '../../Interlinear/05-Deuteronomy/chapter-014.xml',
  '../../Interlinear/05-Deuteronomy/chapter-015.xml',
  '../../Interlinear/05-Deuteronomy/chapter-016.xml',
  '../../Interlinear/05-Deuteronomy/chapter-017.xml',
  '../../Interlinear/05-Deuteronomy/chapter-018.xml',
  '../../Interlinear/05-Deuteronomy/chapter-019.xml',
  '../../Interlinear/05-Deuteronomy/chapter-020.xml',
  '../../Interlinear/05-Deuteronomy/chapter-021.xml',
  '../../Interlinear/05-Deuteronomy/chapter-022.xml',
  '../../Interlinear/05-Deuteronomy/chapter-023.xml',
  '../../Interlinear/05-Deuteronomy/chapter-024.xml',
  '../../Interlinear/05-Deuteronomy/chapter-025.xml',
  '../../Interlinear/05-Deuteronomy/chapter-026.xml',
  '../../Interlinear/05-Deuteronomy/chapter-027.xml',
  '../../Interlinear/05-Deuteronomy/chapter-028.xml',
  '../../Interlinear/05-Deuteronomy/chapter-029.xml',
  '../../Interlinear/05-Deuteronomy/chapter-030.xml',
  '../../Interlinear/05-Deuteronomy/chapter-031.xml',
  '../../Interlinear/05-Deuteronomy/chapter-032.xml',
  '../../Interlinear/05-Deuteronomy/chapter-033.xml',
  '../../Interlinear/05-Deuteronomy/chapter-034.xml',
  '../../Interlinear/06-Joshua/chapter-001.xml',
  '../../Interlinear/06-Joshua/chapter-002.xml',
  '../../Interlinear/06-Joshua/chapter-003.xml',
  '../../Interlinear/06-Joshua/chapter-004.xml',
  '../../Interlinear/06-Joshua/chapter-005.xml',
  '../../Interlinear/06-Joshua/chapter-006.xml',
  '../../Interlinear/06-Joshua/chapter-007.xml',
  '../../Interlinear/06-Joshua/chapter-008.xml',
  '../../Interlinear/06-Joshua/chapter-009.xml',
  '../../Interlinear/06-Joshua/chapter-010.xml',
  '../../Interlinear/06-Joshua/chapter-011.xml',
  '../../Interlinear/06-Joshua/chapter-012.xml',
  '../../Interlinear/06-Joshua/chapter-013.xml',
  '../../Interlinear/06-Joshua/chapter-014.xml',
  '../../Interlinear/06-Joshua/chapter-015.xml',
  '../../Interlinear/06-Joshua/chapter-016.xml',
  '../../Interlinear/06-Joshua/chapter-017.xml',
  '../../Interlinear/06-Joshua/chapter-018.xml',
  '../../Interlinear/06-Joshua/chapter-019.xml',
  '../../Interlinear/06-Joshua/chapter-020.xml',
  '../../Interlinear/06-Joshua/chapter-021.xml',
  '../../Interlinear/06-Joshua/chapter-022.xml',
  '../../Interlinear/06-Joshua/chapter-023.xml',
  '../../Interlinear/06-Joshua/chapter-024.xml',
  '../../Interlinear/07-Judges/chapter-001.xml',
  '../../Interlinear/07-Judges/chapter-002.xml',
  '../../Interlinear/07-Judges/chapter-003.xml',
  '../../Interlinear/07-Judges/chapter-004.xml',
  '../../Interlinear/07-Judges/chapter-005.xml',
  '../../Interlinear/07-Judges/chapter-006.xml',
  '../../Interlinear/07-Judges/chapter-007.xml',
  '../../Interlinear/07-Judges/chapter-008.xml',
  '../../Interlinear/07-Judges/chapter-009.xml',
  '../../Interlinear/07-Judges/chapter-010.xml',
  '../../Interlinear/07-Judges/chapter-011.xml',
  '../../Interlinear/07-Judges/chapter-012.xml',
  '../../Interlinear/07-Judges/chapter-013.xml',
  '../../Interlinear/07-Judges/chapter-014.xml',
  '../../Interlinear/07-Judges/chapter-015.xml',
  '../../Interlinear/07-Judges/chapter-016.xml',
  '../../Interlinear/07-Judges/chapter-017.xml',
  '../../Interlinear/07-Judges/chapter-018.xml',
  '../../Interlinear/07-Judges/chapter-019.xml',
  '../../Interlinear/07-Judges/chapter-020.xml',
  '../../Interlinear/07-Judges/chapter-021.xml',
  '../../Interlinear/08-Ruth/chapter-001.xml',
  '../../Interlinear/08-Ruth/chapter-002.xml',
  '../../Interlinear/08-Ruth/chapter-003.xml',
  '../../Interlinear/08-Ruth/chapter-004.xml',
  '../../Interlinear/09-1 Samuel/chapter-001.xml',
  '../../Interlinear/09-1 Samuel/chapter-002.xml',
  '../../Interlinear/09-1 Samuel/chapter-003.xml',
  '../../Interlinear/09-1 Samuel/chapter-004.xml',
  '../../Interlinear/09-1 Samuel/chapter-005.xml',
  '../../Interlinear/09-1 Samuel/chapter-006.xml',
  '../../Interlinear/09-1 Samuel/chapter-007.xml',
  '../../Interlinear/09-1 Samuel/chapter-008.xml',
  '../../Interlinear/09-1 Samuel/chapter-009.xml',
  '../../Interlinear/09-1 Samuel/chapter-010.xml',
  '../../Interlinear/09-1 Samuel/chapter-011.xml',
  '../../Interlinear/09-1 Samuel/chapter-012.xml',
  '../../Interlinear/09-1 Samuel/chapter-013.xml',
  '../../Interlinear/09-1 Samuel/chapter-014.xml',
  '../../Interlinear/09-1 Samuel/chapter-015.xml',
  '../../Interlinear/09-1 Samuel/chapter-016.xml',
  '../../Interlinear/09-1 Samuel/chapter-017.xml',
  '../../Interlinear/09-1 Samuel/chapter-018.xml',
  '../../Interlinear/09-1 Samuel/chapter-019.xml',
  '../../Interlinear/09-1 Samuel/chapter-020.xml',
  '../../Interlinear/09-1 Samuel/chapter-021.xml',
  '../../Interlinear/09-1 Samuel/chapter-022.xml',
  '../../Interlinear/09-1 Samuel/chapter-023.xml',
  '../../Interlinear/09-1 Samuel/chapter-024.xml',
  '../../Interlinear/09-1 Samuel/chapter-025.xml',
  '../../Interlinear/09-1 Samuel/chapter-026.xml',
  '../../Interlinear/09-1 Samuel/chapter-027.xml',
  '../../Interlinear/09-1 Samuel/chapter-028.xml',
  '../../Interlinear/09-1 Samuel/chapter-029.xml',
  '../../Interlinear/09-1 Samuel/chapter-030.xml',
  '../../Interlinear/09-1 Samuel/chapter-031.xml',
  '../../Interlinear/10-2 Samuel/chapter-001.xml',
  '../../Interlinear/10-2 Samuel/chapter-002.xml',
  '../../Interlinear/10-2 Samuel/chapter-003.xml',
  '../../Interlinear/10-2 Samuel/chapter-004.xml',
  '../../Interlinear/10-2 Samuel/chapter-005.xml',
  '../../Interlinear/10-2 Samuel/chapter-006.xml',
  '../../Interlinear/10-2 Samuel/chapter-007.xml',
  '../../Interlinear/10-2 Samuel/chapter-008.xml',
  '../../Interlinear/10-2 Samuel/chapter-009.xml',
  '../../Interlinear/10-2 Samuel/chapter-010.xml',
  '../../Interlinear/10-2 Samuel/chapter-011.xml',
  '../../Interlinear/10-2 Samuel/chapter-012.xml',
  '../../Interlinear/10-2 Samuel/chapter-013.xml',
  '../../Interlinear/10-2 Samuel/chapter-014.xml',
  '../../Interlinear/10-2 Samuel/chapter-015.xml',
  '../../Interlinear/10-2 Samuel/chapter-016.xml',
  '../../Interlinear/10-2 Samuel/chapter-017.xml',
  '../../Interlinear/10-2 Samuel/chapter-018.xml',
  '../../Interlinear/10-2 Samuel/chapter-019.xml',
  '../../Interlinear/10-2 Samuel/chapter-020.xml',
  '../../Interlinear/10-2 Samuel/chapter-021.xml',
  '../../Interlinear/10-2 Samuel/chapter-022.xml',
  '../../Interlinear/10-2 Samuel/chapter-023.xml',
  '../../Interlinear/10-2 Samuel/chapter-024.xml',
  '../../Interlinear/11-1 Kings/chapter-001.xml',
  '../../Interlinear/11-1 Kings/chapter-002.xml',
  '../../Interlinear/11-1 Kings/chapter-003.xml',
  '../../Interlinear/11-1 Kings/chapter-004.xml',
  '../../Interlinear/11-1 Kings/chapter-005.xml',
  '../../Interlinear/11-1 Kings/chapter-006.xml',
  '../../Interlinear/11-1 Kings/chapter-007.xml',
  '../../Interlinear/11-1 Kings/chapter-008.xml',
  '../../Interlinear/11-1 Kings/chapter-009.xml',
  '../../Interlinear/11-1 Kings/chapter-010.xml',
  '../../Interlinear/11-1 Kings/chapter-011.xml',
  '../../Interlinear/11-1 Kings/chapter-012.xml',
  '../../Interlinear/11-1 Kings/chapter-013.xml',
  '../../Interlinear/11-1 Kings/chapter-014.xml',
  '../../Interlinear/11-1 Kings/chapter-015.xml',
  '../../Interlinear/11-1 Kings/chapter-016.xml',
  '../../Interlinear/11-1 Kings/chapter-017.xml',
  '../../Interlinear/11-1 Kings/chapter-018.xml',
  '../../Interlinear/11-1 Kings/chapter-019.xml',
  '../../Interlinear/11-1 Kings/chapter-020.xml',
  '../../Interlinear/11-1 Kings/chapter-021.xml',
  '../../Interlinear/11-1 Kings/chapter-022.xml',
  '../../Interlinear/12-2 Kings/chapter-001.xml',
  '../../Interlinear/12-2 Kings/chapter-002.xml',
  '../../Interlinear/12-2 Kings/chapter-003.xml',
  '../../Interlinear/12-2 Kings/chapter-004.xml',
  '../../Interlinear/12-2 Kings/chapter-005.xml',
  '../../Interlinear/12-2 Kings/chapter-006.xml',
  '../../Interlinear/12-2 Kings/chapter-007.xml',
  '../../Interlinear/12-2 Kings/chapter-008.xml',
  '../../Interlinear/12-2 Kings/chapter-009.xml',
  '../../Interlinear/12-2 Kings/chapter-010.xml',
  '../../Interlinear/12-2 Kings/chapter-011.xml',
  '../../Interlinear/12-2 Kings/chapter-012.xml',
  '../../Interlinear/12-2 Kings/chapter-013.xml',
  '../../Interlinear/12-2 Kings/chapter-014.xml',
  '../../Interlinear/12-2 Kings/chapter-015.xml',
  '../../Interlinear/12-2 Kings/chapter-016.xml',
  '../../Interlinear/12-2 Kings/chapter-017.xml',
  '../../Interlinear/12-2 Kings/chapter-018.xml',
  '../../Interlinear/12-2 Kings/chapter-019.xml',
  '../../Interlinear/12-2 Kings/chapter-020.xml',
  '../../Interlinear/12-2 Kings/chapter-021.xml',
  '../../Interlinear/12-2 Kings/chapter-022.xml',
  '../../Interlinear/12-2 Kings/chapter-023.xml',
  '../../Interlinear/12-2 Kings/chapter-024.xml',
  '../../Interlinear/12-2 Kings/chapter-025.xml',
  '../../Interlinear/13-1 Chronicles/chapter-001.xml',
  '../../Interlinear/13-1 Chronicles/chapter-002.xml',
  '../../Interlinear/13-1 Chronicles/chapter-003.xml',
  '../../Interlinear/13-1 Chronicles/chapter-004.xml',
  '../../Interlinear/13-1 Chronicles/chapter-005.xml',
  '../../Interlinear/13-1 Chronicles/chapter-006.xml',
  '../../Interlinear/13-1 Chronicles/chapter-007.xml',
  '../../Interlinear/13-1 Chronicles/chapter-008.xml',
  '../../Interlinear/13-1 Chronicles/chapter-009.xml',
  '../../Interlinear/13-1 Chronicles/chapter-010.xml',
  '../../Interlinear/13-1 Chronicles/chapter-011.xml',
  '../../Interlinear/13-1 Chronicles/chapter-012.xml',
  '../../Interlinear/13-1 Chronicles/chapter-013.xml',
  '../../Interlinear/13-1 Chronicles/chapter-014.xml',
  '../../Interlinear/13-1 Chronicles/chapter-015.xml',
  '../../Interlinear/13-1 Chronicles/chapter-016.xml',
  '../../Interlinear/13-1 Chronicles/chapter-017.xml',
  '../../Interlinear/13-1 Chronicles/chapter-018.xml',
  '../../Interlinear/13-1 Chronicles/chapter-019.xml',
  '../../Interlinear/13-1 Chronicles/chapter-020.xml',
  '../../Interlinear/13-1 Chronicles/chapter-021.xml',
  '../../Interlinear/13-1 Chronicles/chapter-022.xml',
  '../../Interlinear/13-1 Chronicles/chapter-023.xml',
  '../../Interlinear/13-1 Chronicles/chapter-024.xml',
  '../../Interlinear/13-1 Chronicles/chapter-025.xml',
  '../../Interlinear/13-1 Chronicles/chapter-026.xml',
  '../../Interlinear/13-1 Chronicles/chapter-027.xml',
  '../../Interlinear/13-1 Chronicles/chapter-028.xml',
  '../../Interlinear/13-1 Chronicles/chapter-029.xml',
  '../../Interlinear/14-2 Chronicles/chapter-001.xml',
  '../../Interlinear/14-2 Chronicles/chapter-002.xml',
  '../../Interlinear/14-2 Chronicles/chapter-003.xml',
  '../../Interlinear/14-2 Chronicles/chapter-004.xml',
  '../../Interlinear/14-2 Chronicles/chapter-005.xml',
  '../../Interlinear/14-2 Chronicles/chapter-006.xml',
  '../../Interlinear/14-2 Chronicles/chapter-007.xml',
  '../../Interlinear/14-2 Chronicles/chapter-008.xml',
  '../../Interlinear/14-2 Chronicles/chapter-009.xml',
  '../../Interlinear/14-2 Chronicles/chapter-010.xml',
  '../../Interlinear/14-2 Chronicles/chapter-011.xml',
  '../../Interlinear/14-2 Chronicles/chapter-012.xml',
  '../../Interlinear/14-2 Chronicles/chapter-013.xml',
  '../../Interlinear/14-2 Chronicles/chapter-014.xml',
  '../../Interlinear/14-2 Chronicles/chapter-015.xml',
  '../../Interlinear/14-2 Chronicles/chapter-016.xml',
  '../../Interlinear/14-2 Chronicles/chapter-017.xml',
  '../../Interlinear/14-2 Chronicles/chapter-018.xml',
  '../../Interlinear/14-2 Chronicles/chapter-019.xml',
  '../../Interlinear/14-2 Chronicles/chapter-020.xml',
  '../../Interlinear/14-2 Chronicles/chapter-021.xml',
  '../../Interlinear/14-2 Chronicles/chapter-022.xml',
  '../../Interlinear/14-2 Chronicles/chapter-023.xml',
  '../../Interlinear/14-2 Chronicles/chapter-024.xml',
  '../../Interlinear/14-2 Chronicles/chapter-025.xml',
  '../../Interlinear/14-2 Chronicles/chapter-026.xml',
  '../../Interlinear/14-2 Chronicles/chapter-027.xml',
  '../../Interlinear/14-2 Chronicles/chapter-028.xml',
  '../../Interlinear/14-2 Chronicles/chapter-029.xml',
  '../../Interlinear/14-2 Chronicles/chapter-030.xml',
  '../../Interlinear/14-2 Chronicles/chapter-031.xml',
  '../../Interlinear/14-2 Chronicles/chapter-032.xml',
  '../../Interlinear/14-2 Chronicles/chapter-033.xml',
  '../../Interlinear/14-2 Chronicles/chapter-034.xml',
  '../../Interlinear/14-2 Chronicles/chapter-035.xml',
  '../../Interlinear/14-2 Chronicles/chapter-036.xml',
  '../../Interlinear/15-Ezra/chapter-001.xml',
  '../../Interlinear/15-Ezra/chapter-002.xml',
  '../../Interlinear/15-Ezra/chapter-003.xml',
  '../../Interlinear/15-Ezra/chapter-004.xml',
  '../../Interlinear/15-Ezra/chapter-005.xml',
  '../../Interlinear/15-Ezra/chapter-006.xml',
  '../../Interlinear/15-Ezra/chapter-007.xml',
  '../../Interlinear/15-Ezra/chapter-008.xml',
  '../../Interlinear/15-Ezra/chapter-009.xml',
  '../../Interlinear/15-Ezra/chapter-010.xml',
  '../../Interlinear/16-Nehemiah/chapter-001.xml',
  '../../Interlinear/16-Nehemiah/chapter-002.xml',
  '../../Interlinear/16-Nehemiah/chapter-003.xml',
  '../../Interlinear/16-Nehemiah/chapter-004.xml',
  '../../Interlinear/16-Nehemiah/chapter-005.xml',
  '../../Interlinear/16-Nehemiah/chapter-006.xml',
  '../../Interlinear/16-Nehemiah/chapter-007.xml',
  '../../Interlinear/16-Nehemiah/chapter-008.xml',
  '../../Interlinear/16-Nehemiah/chapter-009.xml',
  '../../Interlinear/16-Nehemiah/chapter-010.xml',
  '../../Interlinear/16-Nehemiah/chapter-011.xml',
  '../../Interlinear/16-Nehemiah/chapter-012.xml',
  '../../Interlinear/16-Nehemiah/chapter-013.xml',
  '../../Interlinear/17-Esther/chapter-001.xml',
  '../../Interlinear/17-Esther/chapter-002.xml',
  '../../Interlinear/17-Esther/chapter-003.xml',
  '../../Interlinear/17-Esther/chapter-004.xml',
  '../../Interlinear/17-Esther/chapter-005.xml',
  '../../Interlinear/17-Esther/chapter-006.xml',
  '../../Interlinear/17-Esther/chapter-007.xml',
  '../../Interlinear/17-Esther/chapter-008.xml',
  '../../Interlinear/17-Esther/chapter-009.xml',
  '../../Interlinear/17-Esther/chapter-010.xml',
  '../../Interlinear/18-Job/chapter-001.xml',
  '../../Interlinear/18-Job/chapter-002.xml',
  '../../Interlinear/18-Job/chapter-003.xml',
  '../../Interlinear/18-Job/chapter-004.xml',
  '../../Interlinear/18-Job/chapter-005.xml',
  '../../Interlinear/18-Job/chapter-006.xml',
  '../../Interlinear/18-Job/chapter-007.xml',
  '../../Interlinear/18-Job/chapter-008.xml',
  '../../Interlinear/18-Job/chapter-009.xml',
  '../../Interlinear/18-Job/chapter-010.xml',
  '../../Interlinear/18-Job/chapter-011.xml',
  '../../Interlinear/18-Job/chapter-012.xml',
  '../../Interlinear/18-Job/chapter-013.xml',
  '../../Interlinear/18-Job/chapter-014.xml',
  '../../Interlinear/18-Job/chapter-015.xml',
  '../../Interlinear/18-Job/chapter-016.xml',
  '../../Interlinear/18-Job/chapter-017.xml',
  '../../Interlinear/18-Job/chapter-018.xml',
  '../../Interlinear/18-Job/chapter-019.xml',
  '../../Interlinear/18-Job/chapter-020.xml',
  '../../Interlinear/18-Job/chapter-021.xml',
  '../../Interlinear/18-Job/chapter-022.xml',
  '../../Interlinear/18-Job/chapter-023.xml',
  '../../Interlinear/18-Job/chapter-024.xml',
  '../../Interlinear/18-Job/chapter-025.xml',
  '../../Interlinear/18-Job/chapter-026.xml',
  '../../Interlinear/18-Job/chapter-027.xml',
  '../../Interlinear/18-Job/chapter-028.xml',
  '../../Interlinear/18-Job/chapter-029.xml',
  '../../Interlinear/18-Job/chapter-030.xml',
  '../../Interlinear/18-Job/chapter-031.xml',
  '../../Interlinear/18-Job/chapter-032.xml',
  '../../Interlinear/18-Job/chapter-033.xml',
  '../../Interlinear/18-Job/chapter-034.xml',
  '../../Interlinear/18-Job/chapter-035.xml',
  '../../Interlinear/18-Job/chapter-036.xml',
  '../../Interlinear/18-Job/chapter-037.xml',
  '../../Interlinear/18-Job/chapter-038.xml',
  '../../Interlinear/18-Job/chapter-039.xml',
  '../../Interlinear/18-Job/chapter-040.xml',
  '../../Interlinear/18-Job/chapter-041.xml',
  '../../Interlinear/18-Job/chapter-042.xml',
  '../../Interlinear/19-Psalms/chapter-001.xml',
  '../../Interlinear/19-Psalms/chapter-002.xml',
  '../../Interlinear/19-Psalms/chapter-003.xml',
  '../../Interlinear/19-Psalms/chapter-004.xml',
  '../../Interlinear/19-Psalms/chapter-005.xml',
  '../../Interlinear/19-Psalms/chapter-006.xml',
  '../../Interlinear/19-Psalms/chapter-007.xml',
  '../../Interlinear/19-Psalms/chapter-008.xml',
  '../../Interlinear/19-Psalms/chapter-009.xml',
  '../../Interlinear/19-Psalms/chapter-010.xml',
  '../../Interlinear/19-Psalms/chapter-011.xml',
  '../../Interlinear/19-Psalms/chapter-012.xml',
  '../../Interlinear/19-Psalms/chapter-013.xml',
  '../../Interlinear/19-Psalms/chapter-014.xml',
  '../../Interlinear/19-Psalms/chapter-015.xml',
  '../../Interlinear/19-Psalms/chapter-016.xml',
  '../../Interlinear/19-Psalms/chapter-017.xml',
  '../../Interlinear/19-Psalms/chapter-018.xml',
  '../../Interlinear/19-Psalms/chapter-019.xml',
  '../../Interlinear/19-Psalms/chapter-020.xml',
  '../../Interlinear/19-Psalms/chapter-021.xml',
  '../../Interlinear/19-Psalms/chapter-022.xml',
  '../../Interlinear/19-Psalms/chapter-023.xml',
  '../../Interlinear/19-Psalms/chapter-024.xml',
  '../../Interlinear/19-Psalms/chapter-025.xml',
  '../../Interlinear/19-Psalms/chapter-026.xml',
  '../../Interlinear/19-Psalms/chapter-027.xml',
  '../../Interlinear/19-Psalms/chapter-028.xml',
  '../../Interlinear/19-Psalms/chapter-029.xml',
  '../../Interlinear/19-Psalms/chapter-030.xml',
  '../../Interlinear/19-Psalms/chapter-031.xml',
  '../../Interlinear/19-Psalms/chapter-032.xml',
  '../../Interlinear/19-Psalms/chapter-033.xml',
  '../../Interlinear/19-Psalms/chapter-034.xml',
  '../../Interlinear/19-Psalms/chapter-035.xml',
  '../../Interlinear/19-Psalms/chapter-036.xml',
  '../../Interlinear/19-Psalms/chapter-037.xml',
  '../../Interlinear/19-Psalms/chapter-038.xml',
  '../../Interlinear/19-Psalms/chapter-039.xml',
  '../../Interlinear/19-Psalms/chapter-040.xml',
  '../../Interlinear/19-Psalms/chapter-041.xml',
  '../../Interlinear/19-Psalms/chapter-042.xml',
  '../../Interlinear/19-Psalms/chapter-043.xml',
  '../../Interlinear/19-Psalms/chapter-044.xml',
  '../../Interlinear/19-Psalms/chapter-045.xml',
  '../../Interlinear/19-Psalms/chapter-046.xml',
  '../../Interlinear/19-Psalms/chapter-047.xml',
  '../../Interlinear/19-Psalms/chapter-048.xml',
  '../../Interlinear/19-Psalms/chapter-049.xml',
  '../../Interlinear/19-Psalms/chapter-050.xml',
  '../../Interlinear/19-Psalms/chapter-051.xml',
  '../../Interlinear/19-Psalms/chapter-052.xml',
  '../../Interlinear/19-Psalms/chapter-053.xml',
  '../../Interlinear/19-Psalms/chapter-054.xml',
  '../../Interlinear/19-Psalms/chapter-055.xml',
  '../../Interlinear/19-Psalms/chapter-056.xml',
  '../../Interlinear/19-Psalms/chapter-057.xml',
  '../../Interlinear/19-Psalms/chapter-058.xml',
  '../../Interlinear/19-Psalms/chapter-059.xml',
  '../../Interlinear/19-Psalms/chapter-060.xml',
  '../../Interlinear/19-Psalms/chapter-061.xml',
  '../../Interlinear/19-Psalms/chapter-062.xml',
  '../../Interlinear/19-Psalms/chapter-063.xml',
  '../../Interlinear/19-Psalms/chapter-064.xml',
  '../../Interlinear/19-Psalms/chapter-065.xml',
  '../../Interlinear/19-Psalms/chapter-066.xml',
  '../../Interlinear/19-Psalms/chapter-067.xml',
  '../../Interlinear/19-Psalms/chapter-068.xml',
  '../../Interlinear/19-Psalms/chapter-069.xml',
  '../../Interlinear/19-Psalms/chapter-070.xml',
  '../../Interlinear/19-Psalms/chapter-071.xml',
  '../../Interlinear/19-Psalms/chapter-072.xml',
  '../../Interlinear/19-Psalms/chapter-073.xml',
  '../../Interlinear/19-Psalms/chapter-074.xml',
  '../../Interlinear/19-Psalms/chapter-075.xml',
  '../../Interlinear/19-Psalms/chapter-076.xml',
  '../../Interlinear/19-Psalms/chapter-077.xml',
  '../../Interlinear/19-Psalms/chapter-078.xml',
  '../../Interlinear/19-Psalms/chapter-079.xml',
  '../../Interlinear/19-Psalms/chapter-080.xml',
  '../../Interlinear/19-Psalms/chapter-081.xml',
  '../../Interlinear/19-Psalms/chapter-082.xml',
  '../../Interlinear/19-Psalms/chapter-083.xml',
  '../../Interlinear/19-Psalms/chapter-084.xml',
  '../../Interlinear/19-Psalms/chapter-085.xml',
  '../../Interlinear/19-Psalms/chapter-086.xml',
  '../../Interlinear/19-Psalms/chapter-087.xml',
  '../../Interlinear/19-Psalms/chapter-088.xml',
  '../../Interlinear/19-Psalms/chapter-089.xml',
  '../../Interlinear/19-Psalms/chapter-090.xml',
  '../../Interlinear/19-Psalms/chapter-091.xml',
  '../../Interlinear/19-Psalms/chapter-092.xml',
  '../../Interlinear/19-Psalms/chapter-093.xml',
  '../../Interlinear/19-Psalms/chapter-094.xml',
  '../../Interlinear/19-Psalms/chapter-095.xml',
  '../../Interlinear/19-Psalms/chapter-096.xml',
  '../../Interlinear/19-Psalms/chapter-097.xml',
  '../../Interlinear/19-Psalms/chapter-098.xml',
  '../../Interlinear/19-Psalms/chapter-099.xml',
  '../../Interlinear/19-Psalms/chapter-100.xml',
  '../../Interlinear/19-Psalms/chapter-101.xml',
  '../../Interlinear/19-Psalms/chapter-102.xml',
  '../../Interlinear/19-Psalms/chapter-103.xml',
  '../../Interlinear/19-Psalms/chapter-104.xml',
  '../../Interlinear/19-Psalms/chapter-105.xml',
  '../../Interlinear/19-Psalms/chapter-106.xml',
  '../../Interlinear/19-Psalms/chapter-107.xml',
  '../../Interlinear/19-Psalms/chapter-108.xml',
  '../../Interlinear/19-Psalms/chapter-109.xml',
  '../../Interlinear/19-Psalms/chapter-110.xml',
  '../../Interlinear/19-Psalms/chapter-111.xml',
  '../../Interlinear/19-Psalms/chapter-112.xml',
  '../../Interlinear/19-Psalms/chapter-113.xml',
  '../../Interlinear/19-Psalms/chapter-114.xml',
  '../../Interlinear/19-Psalms/chapter-115.xml',
  '../../Interlinear/19-Psalms/chapter-116.xml',
  '../../Interlinear/19-Psalms/chapter-117.xml',
  '../../Interlinear/19-Psalms/chapter-118.xml',
  '../../Interlinear/19-Psalms/chapter-119.xml',
  '../../Interlinear/19-Psalms/chapter-120.xml',
  '../../Interlinear/19-Psalms/chapter-121.xml',
  '../../Interlinear/19-Psalms/chapter-122.xml',
  '../../Interlinear/19-Psalms/chapter-123.xml',
  '../../Interlinear/19-Psalms/chapter-124.xml',
  '../../Interlinear/19-Psalms/chapter-125.xml',
  '../../Interlinear/19-Psalms/chapter-126.xml',
  '../../Interlinear/19-Psalms/chapter-127.xml',
  '../../Interlinear/19-Psalms/chapter-128.xml',
  '../../Interlinear/19-Psalms/chapter-129.xml',
  '../../Interlinear/19-Psalms/chapter-130.xml',
  '../../Interlinear/19-Psalms/chapter-131.xml',
  '../../Interlinear/19-Psalms/chapter-132.xml',
  '../../Interlinear/19-Psalms/chapter-133.xml',
  '../../Interlinear/19-Psalms/chapter-134.xml',
  '../../Interlinear/19-Psalms/chapter-135.xml',
  '../../Interlinear/19-Psalms/chapter-136.xml',
  '../../Interlinear/19-Psalms/chapter-137.xml',
  '../../Interlinear/19-Psalms/chapter-138.xml',
  '../../Interlinear/19-Psalms/chapter-139.xml',
  '../../Interlinear/19-Psalms/chapter-140.xml',
  '../../Interlinear/19-Psalms/chapter-141.xml',
  '../../Interlinear/19-Psalms/chapter-142.xml',
  '../../Interlinear/19-Psalms/chapter-143.xml',
  '../../Interlinear/19-Psalms/chapter-144.xml',
  '../../Interlinear/19-Psalms/chapter-145.xml',
  '../../Interlinear/19-Psalms/chapter-146.xml',
  '../../Interlinear/19-Psalms/chapter-147.xml',
  '../../Interlinear/19-Psalms/chapter-148.xml',
  '../../Interlinear/19-Psalms/chapter-149.xml',
  '../../Interlinear/19-Psalms/chapter-150.xml',
  '../../Interlinear/20-Proverbs/chapter-001.xml',
  '../../Interlinear/20-Proverbs/chapter-002.xml',
  '../../Interlinear/20-Proverbs/chapter-003.xml',
  '../../Interlinear/20-Proverbs/chapter-004.xml',
  '../../Interlinear/20-Proverbs/chapter-005.xml',
  '../../Interlinear/20-Proverbs/chapter-006.xml',
  '../../Interlinear/20-Proverbs/chapter-007.xml',
  '../../Interlinear/20-Proverbs/chapter-008.xml',
  '../../Interlinear/20-Proverbs/chapter-009.xml',
  '../../Interlinear/20-Proverbs/chapter-010.xml',
  '../../Interlinear/20-Proverbs/chapter-011.xml',
  '../../Interlinear/20-Proverbs/chapter-012.xml',
  '../../Interlinear/20-Proverbs/chapter-013.xml',
  '../../Interlinear/20-Proverbs/chapter-014.xml',
  '../../Interlinear/20-Proverbs/chapter-015.xml',
  '../../Interlinear/20-Proverbs/chapter-016.xml',
  '../../Interlinear/20-Proverbs/chapter-017.xml',
  '../../Interlinear/20-Proverbs/chapter-018.xml',
  '../../Interlinear/20-Proverbs/chapter-019.xml',
  '../../Interlinear/20-Proverbs/chapter-020.xml',
  '../../Interlinear/20-Proverbs/chapter-021.xml',
  '../../Interlinear/20-Proverbs/chapter-022.xml',
  '../../Interlinear/20-Proverbs/chapter-023.xml',
  '../../Interlinear/20-Proverbs/chapter-024.xml',
  '../../Interlinear/20-Proverbs/chapter-025.xml',
  '../../Interlinear/20-Proverbs/chapter-026.xml',
  '../../Interlinear/20-Proverbs/chapter-027.xml',
  '../../Interlinear/20-Proverbs/chapter-028.xml',
  '../../Interlinear/20-Proverbs/chapter-029.xml',
  '../../Interlinear/20-Proverbs/chapter-030.xml',
  '../../Interlinear/20-Proverbs/chapter-031.xml',
  '../../Interlinear/21-Ecclesiastes/chapter-001.xml',
  '../../Interlinear/21-Ecclesiastes/chapter-002.xml',
  '../../Interlinear/21-Ecclesiastes/chapter-003.xml',
  '../../Interlinear/21-Ecclesiastes/chapter-004.xml',
  '../../Interlinear/21-Ecclesiastes/chapter-005.xml',
  '../../Interlinear/21-Ecclesiastes/chapter-006.xml',
  '../../Interlinear/21-Ecclesiastes/chapter-007.xml',
  '../../Interlinear/21-Ecclesiastes/chapter-008.xml',
  '../../Interlinear/21-Ecclesiastes/chapter-009.xml',
  '../../Interlinear/21-Ecclesiastes/chapter-010.xml',
  '../../Interlinear/21-Ecclesiastes/chapter-011.xml',
  '../../Interlinear/21-Ecclesiastes/chapter-012.xml',
  '../../Interlinear/22-Ruth/chapter-001.xml',
  '../../Interlinear/22-Ruth/chapter-002.xml',
  '../../Interlinear/22-Ruth/chapter-003.xml',
  '../../Interlinear/22-Ruth/chapter-004.xml',
  '../../Interlinear/22-Ruth/chapter-005.xml',
  '../../Interlinear/22-Ruth/chapter-006.xml',
  '../../Interlinear/22-Ruth/chapter-007.xml',
  '../../Interlinear/22-Ruth/chapter-008.xml',
  '../../Interlinear/23-Isaiah/chapter-001.xml',
  '../../Interlinear/23-Isaiah/chapter-002.xml',
  '../../Interlinear/23-Isaiah/chapter-003.xml',
  '../../Interlinear/23-Isaiah/chapter-004.xml',
  '../../Interlinear/23-Isaiah/chapter-005.xml',
  '../../Interlinear/23-Isaiah/chapter-006.xml',
  '../../Interlinear/23-Isaiah/chapter-007.xml',
  '../../Interlinear/23-Isaiah/chapter-008.xml',
  '../../Interlinear/23-Isaiah/chapter-009.xml',
  '../../Interlinear/23-Isaiah/chapter-010.xml',
  '../../Interlinear/23-Isaiah/chapter-011.xml',
  '../../Interlinear/23-Isaiah/chapter-012.xml',
  '../../Interlinear/23-Isaiah/chapter-013.xml',
  '../../Interlinear/23-Isaiah/chapter-014.xml',
  '../../Interlinear/23-Isaiah/chapter-015.xml',
  '../../Interlinear/23-Isaiah/chapter-016.xml',
  '../../Interlinear/23-Isaiah/chapter-017.xml',
  '../../Interlinear/23-Isaiah/chapter-018.xml',
  '../../Interlinear/23-Isaiah/chapter-019.xml',
  '../../Interlinear/23-Isaiah/chapter-020.xml',
  '../../Interlinear/23-Isaiah/chapter-021.xml',
  '../../Interlinear/23-Isaiah/chapter-022.xml',
  '../../Interlinear/23-Isaiah/chapter-023.xml',
  '../../Interlinear/23-Isaiah/chapter-024.xml',
  '../../Interlinear/23-Isaiah/chapter-025.xml',
  '../../Interlinear/23-Isaiah/chapter-026.xml',
  '../../Interlinear/23-Isaiah/chapter-027.xml',
  '../../Interlinear/23-Isaiah/chapter-028.xml',
  '../../Interlinear/23-Isaiah/chapter-029.xml',
  '../../Interlinear/23-Isaiah/chapter-030.xml',
  '../../Interlinear/23-Isaiah/chapter-031.xml',
  '../../Interlinear/23-Isaiah/chapter-032.xml',
  '../../Interlinear/23-Isaiah/chapter-033.xml',
  '../../Interlinear/23-Isaiah/chapter-034.xml',
  '../../Interlinear/23-Isaiah/chapter-035.xml',
  '../../Interlinear/23-Isaiah/chapter-036.xml',
  '../../Interlinear/23-Isaiah/chapter-037.xml',
  '../../Interlinear/23-Isaiah/chapter-038.xml',
  '../../Interlinear/23-Isaiah/chapter-039.xml',
  '../../Interlinear/23-Isaiah/chapter-040.xml',
  '../../Interlinear/23-Isaiah/chapter-041.xml',
  '../../Interlinear/23-Isaiah/chapter-042.xml',
  '../../Interlinear/23-Isaiah/chapter-043.xml',
  '../../Interlinear/23-Isaiah/chapter-044.xml',
  '../../Interlinear/23-Isaiah/chapter-045.xml',
  '../../Interlinear/23-Isaiah/chapter-046.xml',
  '../../Interlinear/23-Isaiah/chapter-047.xml',
  '../../Interlinear/23-Isaiah/chapter-048.xml',
  '../../Interlinear/23-Isaiah/chapter-049.xml',
  '../../Interlinear/23-Isaiah/chapter-050.xml',
  '../../Interlinear/23-Isaiah/chapter-051.xml',
  '../../Interlinear/23-Isaiah/chapter-052.xml',
  '../../Interlinear/23-Isaiah/chapter-053.xml',
  '../../Interlinear/23-Isaiah/chapter-054.xml',
  '../../Interlinear/23-Isaiah/chapter-055.xml',
  '../../Interlinear/23-Isaiah/chapter-056.xml',
  '../../Interlinear/23-Isaiah/chapter-057.xml',
  '../../Interlinear/23-Isaiah/chapter-058.xml',
  '../../Interlinear/23-Isaiah/chapter-059.xml',
  '../../Interlinear/23-Isaiah/chapter-060.xml',
  '../../Interlinear/23-Isaiah/chapter-061.xml',
  '../../Interlinear/23-Isaiah/chapter-062.xml',
  '../../Interlinear/23-Isaiah/chapter-063.xml',
  '../../Interlinear/23-Isaiah/chapter-064.xml',
  '../../Interlinear/23-Isaiah/chapter-065.xml',
  '../../Interlinear/23-Isaiah/chapter-066.xml',
  '../../Interlinear/24-Jeremiah/chapter-001.xml',
  '../../Interlinear/24-Jeremiah/chapter-002.xml',
  '../../Interlinear/24-Jeremiah/chapter-003.xml',
  '../../Interlinear/24-Jeremiah/chapter-004.xml',
  '../../Interlinear/24-Jeremiah/chapter-005.xml',
  '../../Interlinear/24-Jeremiah/chapter-006.xml',
  '../../Interlinear/24-Jeremiah/chapter-007.xml',
  '../../Interlinear/24-Jeremiah/chapter-008.xml',
  '../../Interlinear/24-Jeremiah/chapter-009.xml',
  '../../Interlinear/24-Jeremiah/chapter-010.xml',
  '../../Interlinear/24-Jeremiah/chapter-011.xml',
  '../../Interlinear/24-Jeremiah/chapter-012.xml',
  '../../Interlinear/24-Jeremiah/chapter-013.xml',
  '../../Interlinear/24-Jeremiah/chapter-014.xml',
  '../../Interlinear/24-Jeremiah/chapter-015.xml',
  '../../Interlinear/24-Jeremiah/chapter-016.xml',
  '../../Interlinear/24-Jeremiah/chapter-017.xml',
  '../../Interlinear/24-Jeremiah/chapter-018.xml',
  '../../Interlinear/24-Jeremiah/chapter-019.xml',
  '../../Interlinear/24-Jeremiah/chapter-020.xml',
  '../../Interlinear/24-Jeremiah/chapter-021.xml',
  '../../Interlinear/24-Jeremiah/chapter-022.xml',
  '../../Interlinear/24-Jeremiah/chapter-023.xml',
  '../../Interlinear/24-Jeremiah/chapter-024.xml',
  '../../Interlinear/24-Jeremiah/chapter-025.xml',
  '../../Interlinear/24-Jeremiah/chapter-026.xml',
  '../../Interlinear/24-Jeremiah/chapter-027.xml',
  '../../Interlinear/24-Jeremiah/chapter-028.xml',
  '../../Interlinear/24-Jeremiah/chapter-029.xml',
  '../../Interlinear/24-Jeremiah/chapter-030.xml',
  '../../Interlinear/24-Jeremiah/chapter-031.xml',
  '../../Interlinear/24-Jeremiah/chapter-032.xml',
  '../../Interlinear/24-Jeremiah/chapter-033.xml',
  '../../Interlinear/24-Jeremiah/chapter-034.xml',
  '../../Interlinear/24-Jeremiah/chapter-035.xml',
  '../../Interlinear/24-Jeremiah/chapter-036.xml',
  '../../Interlinear/24-Jeremiah/chapter-037.xml',
  '../../Interlinear/24-Jeremiah/chapter-038.xml',
  '../../Interlinear/24-Jeremiah/chapter-039.xml',
  '../../Interlinear/24-Jeremiah/chapter-040.xml',
  '../../Interlinear/24-Jeremiah/chapter-041.xml',
  '../../Interlinear/24-Jeremiah/chapter-042.xml',
  '../../Interlinear/24-Jeremiah/chapter-043.xml',
  '../../Interlinear/24-Jeremiah/chapter-044.xml',
  '../../Interlinear/24-Jeremiah/chapter-045.xml',
  '../../Interlinear/24-Jeremiah/chapter-046.xml',
  '../../Interlinear/24-Jeremiah/chapter-047.xml',
  '../../Interlinear/24-Jeremiah/chapter-048.xml',
  '../../Interlinear/24-Jeremiah/chapter-049.xml',
  '../../Interlinear/24-Jeremiah/chapter-050.xml',
  '../../Interlinear/24-Jeremiah/chapter-051.xml',
  '../../Interlinear/24-Jeremiah/chapter-052.xml',
  '../../Interlinear/25-Lamentations/chapter-001.xml',
  '../../Interlinear/25-Lamentations/chapter-002.xml',
  '../../Interlinear/25-Lamentations/chapter-003.xml',
  '../../Interlinear/25-Lamentations/chapter-004.xml',
  '../../Interlinear/25-Lamentations/chapter-005.xml',
  '../../Interlinear/26-Ezekiel/chapter-001.xml',
  '../../Interlinear/26-Ezekiel/chapter-002.xml',
  '../../Interlinear/26-Ezekiel/chapter-003.xml',
  '../../Interlinear/26-Ezekiel/chapter-004.xml',
  '../../Interlinear/26-Ezekiel/chapter-005.xml',
  '../../Interlinear/26-Ezekiel/chapter-006.xml',
  '../../Interlinear/26-Ezekiel/chapter-007.xml',
  '../../Interlinear/26-Ezekiel/chapter-008.xml',
  '../../Interlinear/26-Ezekiel/chapter-009.xml',
  '../../Interlinear/26-Ezekiel/chapter-010.xml',
  '../../Interlinear/26-Ezekiel/chapter-011.xml',
  '../../Interlinear/26-Ezekiel/chapter-012.xml',
  '../../Interlinear/26-Ezekiel/chapter-013.xml',
  '../../Interlinear/26-Ezekiel/chapter-014.xml',
  '../../Interlinear/26-Ezekiel/chapter-015.xml',
  '../../Interlinear/26-Ezekiel/chapter-016.xml',
  '../../Interlinear/26-Ezekiel/chapter-017.xml',
  '../../Interlinear/26-Ezekiel/chapter-018.xml',
  '../../Interlinear/26-Ezekiel/chapter-019.xml',
  '../../Interlinear/26-Ezekiel/chapter-020.xml',
  '../../Interlinear/26-Ezekiel/chapter-021.xml',
  '../../Interlinear/26-Ezekiel/chapter-022.xml',
  '../../Interlinear/26-Ezekiel/chapter-023.xml',
  '../../Interlinear/26-Ezekiel/chapter-024.xml',
  '../../Interlinear/26-Ezekiel/chapter-025.xml',
  '../../Interlinear/26-Ezekiel/chapter-026.xml',
  '../../Interlinear/26-Ezekiel/chapter-027.xml',
  '../../Interlinear/26-Ezekiel/chapter-028.xml',
  '../../Interlinear/26-Ezekiel/chapter-029.xml',
  '../../Interlinear/26-Ezekiel/chapter-030.xml',
  '../../Interlinear/26-Ezekiel/chapter-031.xml',
  '../../Interlinear/26-Ezekiel/chapter-032.xml',
  '../../Interlinear/26-Ezekiel/chapter-033.xml',
  '../../Interlinear/26-Ezekiel/chapter-034.xml',
  '../../Interlinear/26-Ezekiel/chapter-035.xml',
  '../../Interlinear/26-Ezekiel/chapter-036.xml',
  '../../Interlinear/26-Ezekiel/chapter-037.xml',
  '../../Interlinear/26-Ezekiel/chapter-038.xml',
  '../../Interlinear/26-Ezekiel/chapter-039.xml',
  '../../Interlinear/26-Ezekiel/chapter-040.xml',
  '../../Interlinear/26-Ezekiel/chapter-041.xml',
  '../../Interlinear/26-Ezekiel/chapter-042.xml',
  '../../Interlinear/26-Ezekiel/chapter-043.xml',
  '../../Interlinear/26-Ezekiel/chapter-044.xml',
  '../../Interlinear/26-Ezekiel/chapter-045.xml',
  '../../Interlinear/26-Ezekiel/chapter-046.xml',
  '../../Interlinear/26-Ezekiel/chapter-047.xml',
  '../../Interlinear/26-Ezekiel/chapter-048.xml',
  '../../Interlinear/27-Daniel/chapter-001.xml',
  '../../Interlinear/27-Daniel/chapter-002.xml',
  '../../Interlinear/27-Daniel/chapter-003.xml',
  '../../Interlinear/27-Daniel/chapter-004.xml',
  '../../Interlinear/27-Daniel/chapter-005.xml',
  '../../Interlinear/27-Daniel/chapter-006.xml',
  '../../Interlinear/27-Daniel/chapter-007.xml',
  '../../Interlinear/27-Daniel/chapter-008.xml',
  '../../Interlinear/27-Daniel/chapter-009.xml',
  '../../Interlinear/27-Daniel/chapter-010.xml',
  '../../Interlinear/27-Daniel/chapter-011.xml',
  '../../Interlinear/27-Daniel/chapter-012.xml',
  '../../Interlinear/28-Hosea/chapter-001.xml',
  '../../Interlinear/28-Hosea/chapter-002.xml',
  '../../Interlinear/28-Hosea/chapter-003.xml',
  '../../Interlinear/28-Hosea/chapter-004.xml',
  '../../Interlinear/28-Hosea/chapter-005.xml',
  '../../Interlinear/28-Hosea/chapter-006.xml',
  '../../Interlinear/28-Hosea/chapter-007.xml',
  '../../Interlinear/28-Hosea/chapter-008.xml',
  '../../Interlinear/28-Hosea/chapter-009.xml',
  '../../Interlinear/28-Hosea/chapter-010.xml',
  '../../Interlinear/28-Hosea/chapter-011.xml',
  '../../Interlinear/28-Hosea/chapter-012.xml',
  '../../Interlinear/28-Hosea/chapter-013.xml',
  '../../Interlinear/28-Hosea/chapter-014.xml',
  '../../Interlinear/29-Joel/chapter-001.xml',
  '../../Interlinear/29-Joel/chapter-002.xml',
  '../../Interlinear/29-Joel/chapter-003.xml',
  '../../Interlinear/30-Amos/chapter-001.xml',
  '../../Interlinear/30-Amos/chapter-002.xml',
  '../../Interlinear/30-Amos/chapter-003.xml',
  '../../Interlinear/30-Amos/chapter-004.xml',
  '../../Interlinear/30-Amos/chapter-005.xml',
  '../../Interlinear/30-Amos/chapter-006.xml',
  '../../Interlinear/30-Amos/chapter-007.xml',
  '../../Interlinear/30-Amos/chapter-008.xml',
  '../../Interlinear/30-Amos/chapter-009.xml',
  '../../Interlinear/31-Obadiah/chapter-001.xml',
  '../../Interlinear/32-Jonah/chapter-001.xml',
  '../../Interlinear/32-Jonah/chapter-002.xml',
  '../../Interlinear/32-Jonah/chapter-003.xml',
  '../../Interlinear/32-Jonah/chapter-004.xml',
  '../../Interlinear/33-Micah/chapter-001.xml',
  '../../Interlinear/33-Micah/chapter-002.xml',
  '../../Interlinear/33-Micah/chapter-003.xml',
  '../../Interlinear/33-Micah/chapter-004.xml',
  '../../Interlinear/33-Micah/chapter-005.xml',
  '../../Interlinear/33-Micah/chapter-006.xml',
  '../../Interlinear/33-Micah/chapter-007.xml',
  '../../Interlinear/34-Nahum/chapter-001.xml',
  '../../Interlinear/34-Nahum/chapter-002.xml',
  '../../Interlinear/34-Nahum/chapter-003.xml',
  '../../Interlinear/35-Habakkuk/chapter-001.xml',
  '../../Interlinear/35-Habakkuk/chapter-002.xml',
  '../../Interlinear/35-Habakkuk/chapter-003.xml',
  '../../Interlinear/36-Zephaniah/chapter-001.xml',
  '../../Interlinear/36-Zephaniah/chapter-002.xml',
  '../../Interlinear/36-Zephaniah/chapter-003.xml',
  '../../Interlinear/37-Haggai/chapter-001.xml',
  '../../Interlinear/37-Haggai/chapter-002.xml',
  '../../Interlinear/38-Zechariah/chapter-001.xml',
  '../../Interlinear/38-Zechariah/chapter-002.xml',
  '../../Interlinear/38-Zechariah/chapter-003.xml',
  '../../Interlinear/38-Zechariah/chapter-004.xml',
  '../../Interlinear/38-Zechariah/chapter-005.xml',
  '../../Interlinear/38-Zechariah/chapter-006.xml',
  '../../Interlinear/38-Zechariah/chapter-007.xml',
  '../../Interlinear/38-Zechariah/chapter-008.xml',
  '../../Interlinear/38-Zechariah/chapter-009.xml',
  '../../Interlinear/38-Zechariah/chapter-010.xml',
  '../../Interlinear/38-Zechariah/chapter-011.xml',
  '../../Interlinear/38-Zechariah/chapter-012.xml',
  '../../Interlinear/38-Zechariah/chapter-013.xml',
  '../../Interlinear/38-Zechariah/chapter-014.xml',
  '../../Interlinear/39-Malachi/chapter-001.xml',
  '../../Interlinear/39-Malachi/chapter-002.xml',
  '../../Interlinear/39-Malachi/chapter-003.xml',
  '../../Interlinear/39-Malachi/chapter-004.xml',
  '../../Interlinear/40-Matthew/chapter-001.xml',
  '../../Interlinear/40-Matthew/chapter-002.xml',
  '../../Interlinear/40-Matthew/chapter-003.xml',
  '../../Interlinear/40-Matthew/chapter-004.xml',
  '../../Interlinear/40-Matthew/chapter-005.xml',
  '../../Interlinear/40-Matthew/chapter-006.xml',
  '../../Interlinear/40-Matthew/chapter-007.xml',
  '../../Interlinear/40-Matthew/chapter-008.xml',
  '../../Interlinear/40-Matthew/chapter-009.xml',
  '../../Interlinear/40-Matthew/chapter-010.xml',
  '../../Interlinear/40-Matthew/chapter-011.xml',
  '../../Interlinear/40-Matthew/chapter-012.xml',
  '../../Interlinear/40-Matthew/chapter-013.xml',
  '../../Interlinear/40-Matthew/chapter-014.xml',
  '../../Interlinear/40-Matthew/chapter-015.xml',
  '../../Interlinear/40-Matthew/chapter-016.xml',
  '../../Interlinear/40-Matthew/chapter-017.xml',
  '../../Interlinear/40-Matthew/chapter-018.xml',
  '../../Interlinear/40-Matthew/chapter-019.xml',
  '../../Interlinear/40-Matthew/chapter-020.xml',
  '../../Interlinear/40-Matthew/chapter-021.xml',
  '../../Interlinear/40-Matthew/chapter-022.xml',
  '../../Interlinear/40-Matthew/chapter-023.xml',
  '../../Interlinear/40-Matthew/chapter-024.xml',
  '../../Interlinear/40-Matthew/chapter-025.xml',
  '../../Interlinear/40-Matthew/chapter-026.xml',
  '../../Interlinear/40-Matthew/chapter-027.xml',
  '../../Interlinear/40-Matthew/chapter-028.xml',
  '../../Interlinear/41-Mark/chapter-001.xml',
  '../../Interlinear/41-Mark/chapter-002.xml',
  '../../Interlinear/41-Mark/chapter-003.xml',
  '../../Interlinear/41-Mark/chapter-004.xml',
  '../../Interlinear/41-Mark/chapter-005.xml',
  '../../Interlinear/41-Mark/chapter-006.xml',
  '../../Interlinear/41-Mark/chapter-007.xml',
  '../../Interlinear/41-Mark/chapter-008.xml',
  '../../Interlinear/41-Mark/chapter-009.xml',
  '../../Interlinear/41-Mark/chapter-010.xml',
  '../../Interlinear/41-Mark/chapter-011.xml',
  '../../Interlinear/41-Mark/chapter-012.xml',
  '../../Interlinear/41-Mark/chapter-013.xml',
  '../../Interlinear/41-Mark/chapter-014.xml',
  '../../Interlinear/41-Mark/chapter-015.xml',
  '../../Interlinear/41-Mark/chapter-016.xml',
  '../../Interlinear/42-Luke/chapter-001.xml',
  '../../Interlinear/42-Luke/chapter-002.xml',
  '../../Interlinear/42-Luke/chapter-003.xml',
  '../../Interlinear/42-Luke/chapter-004.xml',
  '../../Interlinear/42-Luke/chapter-005.xml',
  '../../Interlinear/42-Luke/chapter-006.xml',
  '../../Interlinear/42-Luke/chapter-007.xml',
  '../../Interlinear/42-Luke/chapter-008.xml',
  '../../Interlinear/42-Luke/chapter-009.xml',
  '../../Interlinear/42-Luke/chapter-010.xml',
  '../../Interlinear/42-Luke/chapter-011.xml',
  '../../Interlinear/42-Luke/chapter-012.xml',
  '../../Interlinear/42-Luke/chapter-013.xml',
  '../../Interlinear/42-Luke/chapter-014.xml',
  '../../Interlinear/42-Luke/chapter-015.xml',
  '../../Interlinear/42-Luke/chapter-016.xml',
  '../../Interlinear/42-Luke/chapter-017.xml',
  '../../Interlinear/42-Luke/chapter-018.xml',
  '../../Interlinear/42-Luke/chapter-019.xml',
  '../../Interlinear/42-Luke/chapter-020.xml',
  '../../Interlinear/42-Luke/chapter-021.xml',
  '../../Interlinear/42-Luke/chapter-022.xml',
  '../../Interlinear/42-Luke/chapter-023.xml',
  '../../Interlinear/42-Luke/chapter-024.xml',
  '../../Interlinear/43-John/chapter-001.xml',
  '../../Interlinear/43-John/chapter-002.xml',
  '../../Interlinear/43-John/chapter-003.xml',
  '../../Interlinear/43-John/chapter-004.xml',
  '../../Interlinear/43-John/chapter-005.xml',
  '../../Interlinear/43-John/chapter-006.xml',
  '../../Interlinear/43-John/chapter-007.xml',
  '../../Interlinear/43-John/chapter-008.xml',
  '../../Interlinear/43-John/chapter-009.xml',
  '../../Interlinear/43-John/chapter-010.xml',
  '../../Interlinear/43-John/chapter-011.xml',
  '../../Interlinear/43-John/chapter-012.xml',
  '../../Interlinear/43-John/chapter-013.xml',
  '../../Interlinear/43-John/chapter-014.xml',
  '../../Interlinear/43-John/chapter-015.xml',
  '../../Interlinear/43-John/chapter-016.xml',
  '../../Interlinear/43-John/chapter-017.xml',
  '../../Interlinear/43-John/chapter-018.xml',
  '../../Interlinear/43-John/chapter-019.xml',
  '../../Interlinear/43-John/chapter-020.xml',
  '../../Interlinear/43-John/chapter-021.xml',
  '../../Interlinear/44-Acts/chapter-001.xml',
  '../../Interlinear/44-Acts/chapter-002.xml',
  '../../Interlinear/44-Acts/chapter-003.xml',
  '../../Interlinear/44-Acts/chapter-004.xml',
  '../../Interlinear/44-Acts/chapter-005.xml',
  '../../Interlinear/44-Acts/chapter-006.xml',
  '../../Interlinear/44-Acts/chapter-007.xml',
  '../../Interlinear/44-Acts/chapter-008.xml',
  '../../Interlinear/44-Acts/chapter-009.xml',
  '../../Interlinear/44-Acts/chapter-010.xml',
  '../../Interlinear/44-Acts/chapter-011.xml',
  '../../Interlinear/44-Acts/chapter-012.xml',
  '../../Interlinear/44-Acts/chapter-013.xml',
  '../../Interlinear/44-Acts/chapter-014.xml',
  '../../Interlinear/44-Acts/chapter-015.xml',
  '../../Interlinear/44-Acts/chapter-016.xml',
  '../../Interlinear/44-Acts/chapter-017.xml',
  '../../Interlinear/44-Acts/chapter-018.xml',
  '../../Interlinear/44-Acts/chapter-019.xml',
  '../../Interlinear/44-Acts/chapter-020.xml',
  '../../Interlinear/44-Acts/chapter-021.xml',
  '../../Interlinear/44-Acts/chapter-022.xml',
  '../../Interlinear/44-Acts/chapter-023.xml',
  '../../Interlinear/44-Acts/chapter-024.xml',
  '../../Interlinear/44-Acts/chapter-025.xml',
  '../../Interlinear/44-Acts/chapter-026.xml',
  '../../Interlinear/44-Acts/chapter-027.xml',
  '../../Interlinear/44-Acts/chapter-028.xml',
  '../../Interlinear/45-Romans/chapter-001.xml',
  '../../Interlinear/45-Romans/chapter-002.xml',
  '../../Interlinear/45-Romans/chapter-003.xml',
  '../../Interlinear/45-Romans/chapter-004.xml',
  '../../Interlinear/45-Romans/chapter-005.xml',
  '../../Interlinear/45-Romans/chapter-006.xml',
  '../../Interlinear/45-Romans/chapter-007.xml',
  '../../Interlinear/45-Romans/chapter-008.xml',
  '../../Interlinear/45-Romans/chapter-009.xml',
  '../../Interlinear/45-Romans/chapter-010.xml',
  '../../Interlinear/45-Romans/chapter-011.xml',
  '../../Interlinear/45-Romans/chapter-012.xml',
  '../../Interlinear/45-Romans/chapter-013.xml',
  '../../Interlinear/45-Romans/chapter-014.xml',
  '../../Interlinear/45-Romans/chapter-015.xml',
  '../../Interlinear/45-Romans/chapter-016.xml',
  '../../Interlinear/46-1 Corinthians/chapter-001.xml',
  '../../Interlinear/46-1 Corinthians/chapter-002.xml',
  '../../Interlinear/46-1 Corinthians/chapter-003.xml',
  '../../Interlinear/46-1 Corinthians/chapter-004.xml',
  '../../Interlinear/46-1 Corinthians/chapter-005.xml',
  '../../Interlinear/46-1 Corinthians/chapter-006.xml',
  '../../Interlinear/46-1 Corinthians/chapter-007.xml',
  '../../Interlinear/46-1 Corinthians/chapter-008.xml',
  '../../Interlinear/46-1 Corinthians/chapter-009.xml',
  '../../Interlinear/46-1 Corinthians/chapter-010.xml',
  '../../Interlinear/46-1 Corinthians/chapter-011.xml',
  '../../Interlinear/46-1 Corinthians/chapter-012.xml',
  '../../Interlinear/46-1 Corinthians/chapter-013.xml',
  '../../Interlinear/46-1 Corinthians/chapter-014.xml',
  '../../Interlinear/46-1 Corinthians/chapter-015.xml',
  '../../Interlinear/46-1 Corinthians/chapter-016.xml',
  '../../Interlinear/47-2 Corinthians/chapter-001.xml',
  '../../Interlinear/47-2 Corinthians/chapter-002.xml',
  '../../Interlinear/47-2 Corinthians/chapter-003.xml',
  '../../Interlinear/47-2 Corinthians/chapter-004.xml',
  '../../Interlinear/47-2 Corinthians/chapter-005.xml',
  '../../Interlinear/47-2 Corinthians/chapter-006.xml',
  '../../Interlinear/47-2 Corinthians/chapter-007.xml',
  '../../Interlinear/47-2 Corinthians/chapter-008.xml',
  '../../Interlinear/47-2 Corinthians/chapter-009.xml',
  '../../Interlinear/47-2 Corinthians/chapter-010.xml',
  '../../Interlinear/47-2 Corinthians/chapter-011.xml',
  '../../Interlinear/47-2 Corinthians/chapter-012.xml',
  '../../Interlinear/47-2 Corinthians/chapter-013.xml',
  '../../Interlinear/48-Galatians/chapter-001.xml',
  '../../Interlinear/48-Galatians/chapter-002.xml',
  '../../Interlinear/48-Galatians/chapter-003.xml',
  '../../Interlinear/48-Galatians/chapter-004.xml',
  '../../Interlinear/48-Galatians/chapter-005.xml',
  '../../Interlinear/48-Galatians/chapter-006.xml',
  '../../Interlinear/49-Ephesians/chapter-001.xml',
  '../../Interlinear/49-Ephesians/chapter-002.xml',
  '../../Interlinear/49-Ephesians/chapter-003.xml',
  '../../Interlinear/49-Ephesians/chapter-004.xml',
  '../../Interlinear/49-Ephesians/chapter-005.xml',
  '../../Interlinear/49-Ephesians/chapter-006.xml',
  '../../Interlinear/50-Philippians/chapter-001.xml',
  '../../Interlinear/50-Philippians/chapter-002.xml',
  '../../Interlinear/50-Philippians/chapter-003.xml',
  '../../Interlinear/50-Philippians/chapter-004.xml',
  '../../Interlinear/51-Colossians/chapter-001.xml',
  '../../Interlinear/51-Colossians/chapter-002.xml',
  '../../Interlinear/51-Colossians/chapter-003.xml',
  '../../Interlinear/51-Colossians/chapter-004.xml',
  '../../Interlinear/52-1 Thessalonians/chapter-001.xml',
  '../../Interlinear/52-1 Thessalonians/chapter-002.xml',
  '../../Interlinear/52-1 Thessalonians/chapter-003.xml',
  '../../Interlinear/52-1 Thessalonians/chapter-004.xml',
  '../../Interlinear/52-1 Thessalonians/chapter-005.xml',
  '../../Interlinear/53-2 Thessalonians/chapter-001.xml',
  '../../Interlinear/53-2 Thessalonians/chapter-002.xml',
  '../../Interlinear/53-2 Thessalonians/chapter-003.xml',
  '../../Interlinear/54-1 Timothy/chapter-001.xml',
  '../../Interlinear/54-1 Timothy/chapter-002.xml',
  '../../Interlinear/54-1 Timothy/chapter-003.xml',
  '../../Interlinear/54-1 Timothy/chapter-004.xml',
  '../../Interlinear/54-1 Timothy/chapter-005.xml',
  '../../Interlinear/54-1 Timothy/chapter-006.xml',
  '../../Interlinear/55-2 Timothy/chapter-001.xml',
  '../../Interlinear/55-2 Timothy/chapter-002.xml',
  '../../Interlinear/55-2 Timothy/chapter-003.xml',
  '../../Interlinear/55-2 Timothy/chapter-004.xml',
  '../../Interlinear/56-Titus/chapter-001.xml',
  '../../Interlinear/56-Titus/chapter-002.xml',
  '../../Interlinear/56-Titus/chapter-003.xml',
  '../../Interlinear/57-Philemon/chapter-001.xml',
  '../../Interlinear/58-Hebrews/chapter-001.xml',
  '../../Interlinear/58-Hebrews/chapter-002.xml',
  '../../Interlinear/58-Hebrews/chapter-003.xml',
  '../../Interlinear/58-Hebrews/chapter-004.xml',
  '../../Interlinear/58-Hebrews/chapter-005.xml',
  '../../Interlinear/58-Hebrews/chapter-006.xml',
  '../../Interlinear/58-Hebrews/chapter-007.xml',
  '../../Interlinear/58-Hebrews/chapter-008.xml',
  '../../Interlinear/58-Hebrews/chapter-009.xml',
  '../../Interlinear/58-Hebrews/chapter-010.xml',
  '../../Interlinear/58-Hebrews/chapter-011.xml',
  '../../Interlinear/58-Hebrews/chapter-012.xml',
  '../../Interlinear/58-Hebrews/chapter-013.xml',
  '../../Interlinear/59-James/chapter-001.xml',
  '../../Interlinear/59-James/chapter-002.xml',
  '../../Interlinear/59-James/chapter-003.xml',
  '../../Interlinear/59-James/chapter-004.xml',
  '../../Interlinear/59-James/chapter-005.xml',
  '../../Interlinear/60-1 Peter/chapter-001.xml',
  '../../Interlinear/60-1 Peter/chapter-002.xml',
  '../../Interlinear/60-1 Peter/chapter-003.xml',
  '../../Interlinear/60-1 Peter/chapter-004.xml',
  '../../Interlinear/60-1 Peter/chapter-005.xml',
  '../../Interlinear/61-2 Peter/chapter-001.xml',
  '../../Interlinear/61-2 Peter/chapter-002.xml',
  '../../Interlinear/61-2 Peter/chapter-003.xml',
  '../../Interlinear/62-1 John/chapter-001.xml',
  '../../Interlinear/62-1 John/chapter-002.xml',
  '../../Interlinear/62-1 John/chapter-003.xml',
  '../../Interlinear/62-1 John/chapter-004.xml',
  '../../Interlinear/62-1 John/chapter-005.xml',
  '../../Interlinear/63-2 John/chapter-001.xml',
  '../../Interlinear/64-3 John/chapter-001.xml',
  '../../Interlinear/65-Jude/chapter-001.xml',
  '../../Interlinear/66-Revelation/chapter-001.xml',
  '../../Interlinear/66-Revelation/chapter-002.xml',
  '../../Interlinear/66-Revelation/chapter-003.xml',
  '../../Interlinear/66-Revelation/chapter-004.xml',
  '../../Interlinear/66-Revelation/chapter-005.xml',
  '../../Interlinear/66-Revelation/chapter-006.xml',
  '../../Interlinear/66-Revelation/chapter-007.xml',
  '../../Interlinear/66-Revelation/chapter-008.xml',
  '../../Interlinear/66-Revelation/chapter-009.xml',
  '../../Interlinear/66-Revelation/chapter-010.xml',
  '../../Interlinear/66-Revelation/chapter-011.xml',
  '../../Interlinear/66-Revelation/chapter-012.xml',
  '../../Interlinear/66-Revelation/chapter-013.xml',
  '../../Interlinear/66-Revelation/chapter-014.xml',
  '../../Interlinear/66-Revelation/chapter-015.xml',
  '../../Interlinear/66-Revelation/chapter-016.xml',
  '../../Interlinear/66-Revelation/chapter-017.xml',
  '../../Interlinear/66-Revelation/chapter-018.xml',
  '../../Interlinear/66-Revelation/chapter-019.xml',
  '../../Interlinear/66-Revelation/chapter-020.xml',
  '../../Interlinear/66-Revelation/chapter-021.xml',
  '../../Interlinear/66-Revelation/chapter-022.xml'
];

const makeBookSelectOnChange = (hierarchy, chapterSelect, goSubmit) => {
  const XHTML_NS = 'http://www.w3.org/1999/xhtml';

  const currParts = decodeURI(window.location.pathname).split('/').slice(-2);
  const currBook = currParts[0];
  const currChapter = currParts[1];

  return (e) => {
    // Remove all chapters.
    chapterSelect.textContent = '';

    const book = e.target.value;
    let num = 1;
    let currXML;

    for (const xml of hierarchy[book]) {
      const option = document.createElementNS(XHTML_NS, 'option');
      option.setAttribute('value', xml);

      const parts = xml.split('/').slice(-2);
      const chapter = parts[1];
      let text = num;
      if (book === currBook && chapter === currChapter) {
        text = text + ' •';
        currXML = xml;
      }
      option.appendChild(document.createTextNode(text));
      chapterSelect.appendChild(option);
      num += 1;
    }

    if (typeof currXML === 'string') {
      chapterSelect.value = currXML;
    }
    chapterSelect.onchange = (e) => {
      goSubmit.setAttribute('formaction', chapterSelect.value);
    };
    chapterSelect.dispatchEvent(new Event('change'));
  };
};

const initializeNavigation = () => {
  const XHTML_NS = 'http://www.w3.org/1999/xhtml';

  // First convert the interlinearXMLs to a hierarchy.
  let hierarchy = {};  // Maps from directory name to a list of files there.
  let books = [];      // Keeps the list of books ordered.

  for (const xml of interlinearXMLs) {
    const parts = xml.split('/').slice(-2);
    const book = parts[0];
    if (book in hierarchy === false) {
      hierarchy[book] = [];
      books.push(book);
    }
    hierarchy[book].push(xml);
  }

  const currParts = decodeURI(window.location.pathname).split('/').slice(-2);
  const currBook = currParts[0];
  const currChapter = currParts[1];

  const nav = document.createElementNS(XHTML_NS, 'nav');
  const navForm = document.createElementNS(XHTML_NS, 'form');
  nav.appendChild(navForm);

  const bookSelect = document.createElementNS(XHTML_NS, 'select');
  navForm.appendChild(bookSelect);

  navForm.appendChild(document.createTextNode(' ❯ '));

  const chapterSelect = document.createElementNS(XHTML_NS, 'select');
  navForm.appendChild(chapterSelect);

  navForm.appendChild(document.createTextNode(' ❯ '));

  const goSubmit = document.createElementNS(XHTML_NS, 'input');
  goSubmit.setAttribute('type', 'submit');
  goSubmit.setAttribute('value', '🔎');
  navForm.appendChild(goSubmit);

  for (const book of books) {
    const parts = book.split('-');
    let text = parts[1];

    const option = document.createElementNS(XHTML_NS, 'option');
    option.setAttribute('value', book);
    if (currBook == book) {
      text += ' •';
    }
    option.appendChild(document.createTextNode(text));
    bookSelect.appendChild(option);
  }

  const selectOnChange = makeBookSelectOnChange(
    hierarchy, chapterSelect, goSubmit);
  bookSelect.addEventListener('change', selectOnChange);
  bookSelect.value = currBook;
  bookSelect.dispatchEvent(new Event('change'));

  document.documentElement.insertBefore(
    nav, document.documentElement.firstChild);
};
